### ISSUE TITLE
XF Sample

### ISSUE THREAD

**Issue by capybarbu** [CartoDB/mobile-dotnet-samples#11]
Hi,

I tried what was described in #7 and it seems that it doesn't work very well.

Is it possible to have a real sample project with new namespaces and PCL support ?

Thanks in advance.

**Comment by Nikituh** [comment]
Hey there,

We have an existing forms sample available [here](https://github.com/CartoDB/mobile-dotnet-samples/tree/master/HelloMap.Forms)

You're right, the snippet jaak posted there doesn't work all that well, but a working version is available [here](https://github.com/CartoDB/mobile-dotnet-samples/blob/master/HelloMap.Forms/HelloMap.Forms/MainPage.cs)

The existing sample relies on [native embedding](https://developer.xamarin.com/guides/xamarin-forms/user-interface/layouts/add-platform-controls/), supported as of Xamarin.Forms 2.0, as it is a simpler way to use native elements in a cross-platform project. Additionally, it works wonderfully with our SDK, since **the API (incl. namespaces) is 100% the same across platforms**.

However, if you write a [custom renderer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/custom-renderer/), it's possible to realize the UI via xaml as well.

And, sadly, PCL isn't supported, as our MapView is a native element. 

Best wishes
Aare
CARTO Mobile

**Comment by capybarbu** [comment]
Oh, missed it.

Thanks !
